remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
lang: zh-CN
title: Neko's imagination box
url: https://aneko.moe
twitter_username: anyneko_
github_username: anyneko
author:
    name: Neko in an endless loop.
read_time: true
