#remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
theme: next
language: zh-CN
lang: zh-CN
title: Neko's imagination box
description: 奇迹与魔法都是存在的！
url: https://aneko.moe
twitter_username: anyneko_
github_username: anyneko
author:
    name: Neko in an endless loop.
read_time: true
